# Generated by Django 5.2.4 on 2025-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('editor', 'Editor'), ('reporter', 'Reporter')], default='member', max_length=20),
        ),
    ]
