# Generated by Django 5.2.4 on 2025-08-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
