# Generated by Django 5.2.4 on 2025-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_news_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='कुवेतमा रोजगारी', max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('pre_approval_date', models.CharField(blank=True, max_length=50)),
                ('chalani_no', models.CharField(blank=True, max_length=50)),
                ('lot_no', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('male_count', models.CharField(default='0', max_length=10)),
                ('female_count', models.CharField(default='0', max_length=10)),
                ('salary_kd', models.CharField(blank=True, max_length=50)),
                ('salary_npr', models.CharField(blank=True, max_length=50)),
                ('overtime', models.CharField(default='छ', max_length=100)),
                ('hours_per_day', models.CharField(default='8', max_length=10)),
                ('days_per_week', models.CharField(default='6', max_length=10)),
                ('yearly_leave', models.CharField(default='छ', max_length=100)),
                ('min_qualification', models.CharField(default='कम्तिमा पनि निम्नलिखित मुख्य', max_length=200)),
                ('food_provided', models.CharField(default='छ', max_length=10)),
                ('housing_provided', models.CharField(default='छ', max_length=10)),
                ('contract_duration', models.CharField(default='2 वर्ष', max_length=50)),
                ('application_deadline', models.CharField(blank=True, max_length=100)),
                ('medical_cost_local', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('medical_cost_foreign', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('insurance_local', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('insurance_employment', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('air_ticket', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('visa_fee', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('visa_stamp_fee', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('recruitment_fee', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('welfare_fund', models.CharField(default='रु. ७०० /-', max_length=100)),
                ('labor_fee', models.CharField(default='कामदारले तिर्ने रु. १५०० /-', max_length=100)),
                ('service_fee', models.CharField(default='कामदारले तिर्ने', max_length=100)),
                ('extra_notes', models.TextField(blank=True)),
                ('company_logo_text', models.CharField(default='LOGO', max_length=50)),
                ('company_banner_title', models.CharField(default='BEST EMPLOYMENT HR SOLUTION', max_length=200)),
                ('company_address', models.CharField(default='ठेगाना: Kathmandu-9, Gaushala, Nepal.', max_length=300)),
                ('company_phone', models.CharField(default='फोन: +977-1-5922788', max_length=100)),
                ('company_email', models.CharField(default='इमेल: info@besthr.com.np, bestemploymenthr123@gmail.com', max_length=200)),
                ('company_website', models.CharField(default='वेब: www.besthr.com.np', max_length=100)),
                ('license_number', models.CharField(default='Gov. Lic. Number 1714/081/082', max_length=100)),
                ('ocr_text', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employment Advertisement',
                'verbose_name_plural': 'Employment Advertisements',
            },
        ),
    ]
