# Generated by Django 5.2.4 on 2025-08-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employmentad'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='country',
            field=models.CharField(default='Kuwait', help_text='Country where the job is located', max_length=100),
        ),
    ]
