# Generated by Django 5.2.4 on 2025-08-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employmentad_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentad',
            name='contract_duration',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='female_count',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='food_provided',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='hours_per_day',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='housing_provided',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='male_count',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='min_qualification',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='overtime',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='salary_kd',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='salary_npr',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='yearly_leave',
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('male_count', models.CharField(default='0', max_length=10)),
                ('female_count', models.CharField(default='0', max_length=10)),
                ('salary_kd', models.CharField(blank=True, max_length=50)),
                ('salary_npr', models.CharField(blank=True, max_length=50)),
                ('overtime', models.CharField(default='छ', max_length=100)),
                ('hours_per_day', models.CharField(default='8', max_length=10)),
                ('days_per_week', models.CharField(default='6', max_length=10)),
                ('yearly_leave', models.CharField(default='छ', max_length=100)),
                ('min_qualification', models.CharField(default='कम्तिमा पनि निम्नलिखित मुख्य', max_length=200)),
                ('food_provided', models.CharField(default='छ', max_length=10)),
                ('housing_provided', models.CharField(default='छ', max_length=10)),
                ('contract_duration', models.CharField(default='2 वर्ष', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('employment_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.employmentad')),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'ordering': ['order'],
            },
        ),
    ]
