# Generated by Django 5.2.4 on 2025-08-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_employmentad_contract_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='salary_kd',
        ),
        migrations.AddField(
            model_name='employmentad',
            name='interview_date',
            field=models.CharField(blank=True, help_text='Interview date and location', max_length=100),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='salary_amount',
            field=models.CharField(blank=True, help_text='Salary amount', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='salary_currency',
            field=models.CharField(choices=[('KD', 'Kuwaiti Dinar (KD)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('SAR', 'Saudi Riyal (SAR)'), ('AED', 'UAE Dirham (AED)'), ('QAR', 'Qatar Riyal (QAR)'), ('OMR', 'Omani Rial (OMR)'), ('BHD', 'Bahraini Dinar (BHD)'), ('KWD', 'Kuwaiti Dinar (KWD)'), ('NPR', 'Nepali Rupee (रु.)')], default='KD', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='salary_npr',
            field=models.CharField(blank=True, help_text='Salary in Nepali Rupees (auto-calculated)', max_length=50),
        ),
    ]
