# Generated by Django 5.2.4 on 2025-08-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_jobposition_salary_kd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_date',
        ),
    ]
