# Generated by Django 5.2.4 on 2025-08-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_employmentad_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='person_name',
            field=models.CharField(default='Prashish Sapkota', help_text='Name of the person', max_length=200),
        ),
    ]
