# Generated by Django 5.2.4 on 2025-08-24 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employmentad_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='Currency code (e.g., USD, EUR, GBP)', max_length=10, unique=True)),
                ('currency_name', models.CharField(help_text='Currency name', max_length=50)),
                ('rate_to_npr', models.DecimalField(decimal_places=4, help_text='Exchange rate to Nepali Rupees', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(default='अन्तर्वार्ता', help_text='Type of interview (e.g., अन्तर्वार्ता, मुलाकात)', max_length=50)),
                ('nepali_date', models.CharField(blank=True, help_text='Nepali date (e.g., २०८१/१२/१८)', max_length=20)),
                ('gregorian_date', models.CharField(blank=True, help_text='Gregorian date (e.g., 31 मार्च, 2025)', max_length=20)),
                ('time', models.CharField(blank=True, help_text='Time (e.g., बिहान 11 बजे)', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Location (e.g., म्यानपावरको कार्यालय बसुन्धारामा)', max_length=200)),
                ('template', models.CharField(default='अन्तर्वार्ता: मिति {nepali_date} गते ({gregorian_date}) {time} {location} हुनेछ।', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('employment_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.employmentad')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['order'],
            },
        ),
    ]
