# Generated by Django 5.2.4 on 2025-08-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_currencyrate_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='days_per_week',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='female_count',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='food_provided',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='hours_per_day',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='housing_provided',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='male_count',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='min_qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='overtime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='yearly_leave',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
