# Generated by Django 5.2.4 on 2025-08-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_jobposition_contract_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentad',
            name='title',
            field=models.CharField(default='जापानमा रोजगारी', max_length=200),
        ),
    ]
