# Generated by Django 5.2.4 on 2025-08-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_employmentad_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='company_logo_image',
            field=models.ImageField(blank=True, help_text='Upload company logo (recommended size: 70x28px)', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='template',
            field=models.CharField(default='अन्तरवार्ता मिति {nepali_date} ({gregorian_date}) {location} हुनेछ।', max_length=500),
        ),
    ]
