# Generated by Django 5.2.4 on 2025-08-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_employmentad_company_logo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='interview_custom_text',
            field=models.TextField(blank=True, help_text='Custom interview text (leave blank for automatic 8-day calculation)'),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the job is located', max_length=100),
        ),
    ]
