# Generated by Django 5.2.4 on 2025-08-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_employmentad_interview_custom_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='interview_gregorian_date',
            field=models.CharField(blank=True, help_text='Interview date in English format', max_length=50),
        ),
        migrations.AddField(
            model_name='employmentad',
            name='interview_location',
            field=models.CharField(blank=True, default='म्यानपावरको कार्यालयमा', help_text='Interview location', max_length=200),
        ),
        migrations.AddField(
            model_name='employmentad',
            name='interview_nepali_date',
            field=models.CharField(blank=True, help_text='Interview date in Nepali format', max_length=50),
        ),
    ]
