# Generated by Django 5.2.4 on 2025-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_employmentad_interview_gregorian_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_gregorian_date',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_location',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_nepali_date',
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='country',
            field=models.CharField(default='Kuwait', help_text='Country where the job is located', max_length=100),
        ),
    ]
