# Generated by Django 5.2.4 on 2025-09-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_employmentad_interview_gregorian_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='right_section_text',
            field=models.CharField(blank=True, help_text='Text to display in right corner of company row (optional)', max_length=50),
        ),
    ]
