# Generated by Django 5.2.4 on 2025-09-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_employmentad_right_section_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='min_qualification',
            field=models.CharField(blank=True, default='कम्तिमा पनि निम्नलिखित मुख्य', max_length=200),
        ),
    ]
