# Generated by Django 5.2.4 on 2025-09-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_jobposition_min_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='min_qualification',
            field=models.CharField(blank=True, default='कम्पनीको नियमानुसर', max_length=200),
        ),
    ]
