# Generated by Django 5.2.4 on 2025-09-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_jobposition_min_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='interview_gregorian_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmentad',
            name='interview_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employmentad',
            name='interview_nepali_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
