# Generated by Django 5.2.4 on 2025-09-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_employmentad_interview_gregorian_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_gregorian_date',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_location',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_nepali_date',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='right_section_text',
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='min_qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
