# Generated by Django 5.2.4 on 2025-09-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_employmentad_interview_gregorian_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='company_banner_image',
            field=models.ImageField(blank=True, help_text='Upload company banner (recommended size: 12cm x 1.2cm)', null=True, upload_to='company_banners/'),
        ),
    ]
