# Generated by Django 5.2.4 on 2025-09-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_employmentad_company_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='company_banner_text',
            field=models.CharField(blank=True, help_text='Manual banner text (if no image uploaded)', max_length=200),
        ),
    ]
