# Generated by Django 5.2.4 on 2025-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_salary_currency_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentad',
            name='air_ticket',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='company_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='company_banner_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='company_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='company_logo_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='company_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='company_website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the job is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='insurance_employment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='insurance_local',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='labor_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='medical_cost_foreign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='medical_cost_local',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='person_name',
            field=models.CharField(blank=True, help_text='Name of the person', max_length=200),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='recruitment_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='service_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='visa_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='visa_stamp_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentad',
            name='welfare_fund',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
