# Generated by Django 5.2.4 on 2025-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_employment_ad_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentad',
            name='interview_gregorian_date',
            field=models.CharField(blank=True, help_text='Gregorian date (e.g., 31 मार्च, 2025)', max_length=20),
        ),
        migrations.AddField(
            model_name='employmentad',
            name='interview_location',
            field=models.CharField(blank=True, help_text='Interview location', max_length=200),
        ),
        migrations.AddField(
            model_name='employmentad',
            name='interview_nepali_date',
            field=models.CharField(blank=True, help_text='Nepali date (e.g., २०८१/१२/१८)', max_length=20),
        ),
    ]
