# Generated by Django 5.2.4 on 2025-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_employmentad_interview_gregorian_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_gregorian_date',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_location',
        ),
        migrations.RemoveField(
            model_name='employmentad',
            name='interview_nepali_date',
        ),
        migrations.AddField(
            model_name='employmentad',
            name='right_section_text',
            field=models.CharField(blank=True, help_text='Text to display in right corner of company row (optional)', max_length=50),
        ),
    ]
