# Generated by Django 5.2.4 on 2025-09-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_employmentad_interview_gregorian_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('JPY', 'Japanese Yen (¥)'), ('KD', 'Kuwaiti Dinar (KD)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('SAR', 'Saudi Riyal (SAR)'), ('AED', 'UAE Dirham (AED)'), ('QAR', 'Qatar Riyal (QAR)'), ('OMR', 'Omani Rial (OMR)'), ('BHD', 'Bahraini Dinar (BHD)'), ('KWD', 'Kuwaiti Dinar (KWD)'), ('NPR', 'Nepali Rupee (रु.)')], max_length=10),
        ),
    ]
